language: java

jdk:
  - oraclejdk8

#Because oracleJDK8 may not be available...
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
  postgresql: "9.4"

# Peculiarity with dependency caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -f sql/setup.sql -d travis_ci_test -U postgres
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/